Traceback (most recent call last):
  File "/home/qc/Master-Thesis/multilang-stacktrace/python/main2.py", line 15, in <module>
    main()
  File "/home/qc/Master-Thesis/multilang-stacktrace/python/main2.py", line 11, in main
    result = foo(array, 6)
  File "/home/qc/Master-Thesis/multilang-stacktrace/python/main2.py", line 7, in foo
    return foo(array, counter - 1)
  File "/home/qc/Master-Thesis/multilang-stacktrace/python/main2.py", line 7, in foo
    return foo(array, counter - 1)
  File "/home/qc/Master-Thesis/multilang-stacktrace/python/main2.py", line 7, in foo
    return foo(array, counter - 1)
  [Previous line repeated 3 more times]
  File "/home/qc/Master-Thesis/multilang-stacktrace/python/main2.py", line 6, in foo
    return dangerous(array, counter + 9137)
  File "/home/qc/Master-Thesis/multilang-stacktrace/python/main2.py", line 2, in dangerous
    return array[index]
IndexError: list index out of range
