
thread 'main' panicked at rust/main.rs:1:58:
index out of bounds: the len is 1000 but the index is 15206
stack backtrace:
   0: __rustc::rust_begin_unwind
             at /rustc/17067e9ac6d7ecb70e50f92c1944e545188d2359/library/std/src/panicking.rs:697:5
   1: core::panicking::panic_fmt
             at /rustc/17067e9ac6d7ecb70e50f92c1944e545188d2359/library/core/src/panicking.rs:75:14
   2: core::panicking::panic_bounds_check
             at /rustc/17067e9ac6d7ecb70e50f92c1944e545188d2359/library/core/src/panicking.rs:273:5
   3: <usize as core::slice::index::SliceIndex<[T]>>::index
             at /home/qc/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/index.rs:274:10
   4: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at /home/qc/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/index.rs:16:9
   5: <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index
             at /home/qc/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:3372:9
   6: main::dangerous
             at ./rust/main.rs:1:58
   7: main::foo
             at ./rust/main.rs:2:47
   8: main::foo1
             at ./rust/main.rs:3:48
   9: main::foo2
             at ./rust/main.rs:4:48
  10: main::foo3
             at ./rust/main.rs:5:48
  11: main::foo4
             at ./rust/main.rs:6:48
  12: main::foo5
             at ./rust/main.rs:7:48
  13: main::foo6
             at ./rust/main.rs:8:48
  14: main::main
             at ./rust/main.rs:11:20
  15: core::ops::function::FnOnce::call_once
             at /home/qc/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
